# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYo7ZIcAuh2XMM9kqQgHLf6vFzYvzKR6

Bài 03. Viết chương trình tạo ra list mới bằng cách ghép một chuỗi s vào các phần tử list cũ.
"""

my_list = [1, 2, 'python', 'core', 2, 1 ]
s = input('nhập chuỗi s: ')
my_list.append(s)
print(my_list)