# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEqoJCSAx6XNU-1ZCikVeA5NqaLGGoHv

Bài 04. Viết chương trình chia một list thành 2 phần với độ dài phần đầu được nhập vào từ bàn phím.
"""

my_list = [1, 3, 5, 7, 'lesson6', 'python', 10, 20, 3.14]
len= int(input('nhập độ dài của list muốn tạo : '))
print('s1 = ', my_list[:len],'s2 = ', my_list[len:])