# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BuXZ0xqSZn1BJ7kHZFtHGeus5EpbW3s

Bài 05. Viết chương trình in ra phần tử có số lần xuất hiện nhiều nhất trong một list. Nếu có nhiều phần tử có cùng số lần xuất hiện nhiều nhất thì in ra 1 trong số chúng.
"""

my_list= [0, 4, 1, 1, 0, 8, 3, 7, 1, 7, 6, 1, 0, 0, 1]
count = 0
for i in my_list :
  if my_list.count(i) >= count :
    count = my_list.count(i)
print(i)