# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtlGuJ6VB-orSoKA0HJIkJtuQx2jk1Lt

Bài 07. Viết chương trình kiểm tra 2 list có phần tử chung hay không.
"""

list1=[0, 4, 3, 1, 2, 5, 9, 6]
list2=[3,0,7]
for i in list2 :
  if i in list1:
    print('co phan tu chung la : ', i)