# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zG2cCi2cypAuxoSA0GXopOxfbceitZKh

Bài 02. Viết chương trình tìm số lớn nhất, nhỏ nhất trong một list.
"""

my_list=[-10, -5 , 1, 0, - 15, 5, 13, 19]
max=0
min=0
for i in my_list:
  if i>=max :
    max=i
  if i<=min :
    min=i
print('giá trị lớn nhất và nhỏ nhất trong list lần lượt là : ',max,' và ', min)

