# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzeMEEnklKh5BbH8Xw8zwLV2xE078vIM

Bài 01. Viết chương trình tính tổng, tích của các phần tử trong một list.
"""

my_list=[1, 5, 3, 9, 10, 100, 2021 ]
tong=0
tich=1
for i in my_list :
  tong += i 
  tich *= i
print('tổng của các phần tử là : ',tong)
print('tích của các phần tử là : ',tich)