# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJUCK-OPUQV_EfK1h3mlELYsMkrPATb2

Bài 01: Xem code đã có trong file btvn_01_dog.py (link file đính kèm).
    Viết đoạn chương trình vào tiếp trong file đó để giải quyết yêu cầu sau:
        - Tạo ra 3 đối tượng Dog với các thuộc tính về age khác nhau:
            name        age
            Fake         2
            Mickey       7
            Fuk          5
        - Sau đó, viết một hàm get_biggest_number(*args) nhận vào nhiều tham số, sau đó trả về số lớn nhất.
        - Và dựa trên hàm này, hay tìm và in ra có dạng như sau:
            The oldest dog is 7 years old.
"""

class Dog:
  species = 'mammal'

  def __init__(self, name, age):
    self.name = name
    self.age = age

  def get_biggest_number(self,a,b,c):
    ''' hàm nhận vào nhiều tham số, sau đó trả về số lớn nhất
    '''
    self.a = a
    self.b = b
    self.c = c
    return max(a,b,c)
    
dog1 = Dog('Fake', 2)
dog2 = Dog('Mickey', 7)
dog3 = Dog('Fuk', 5)
print(f'The oldest dog is {get_biggest_number(dog1.age,dog2.age,dog3.age)} years old')

def get_biggest_number(a,b,c):
  
    return max(a,b,c)
print(get_biggest_number(5,6,7))