# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dCxG_OekBRjfU4JlD5IReyyJ0-gxKzUf

Bài tập 3
"""

a = float(input('nhập giá trị của a = '))
b= float(input('nhập giá trị trị của b = '))
print(f'phần nguyên của phép chia là : ',a//b)
print(f'phần dư của phép chia là : ',a%b)