# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nRP30kOlWSiYXANF3s-0oDECK0pmsLw6

Bài tập 1
"""

age = int(input(" nhập tuổi của bạn : "))
income = float(input(" nhập thu nhập hàng năm của bạn : " ))
print(f'điều kiện để vay ngân hàng của bạn là :', age >=18 and income >= 2500)