# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYDlEef98TnJMfms-ox4R9euFbs_cJAp
"""

x= int(input('nhap gia tri cua x '))
n= int(input('nhap gia tri cua n '))
s_3=0
for i in range(n+1):
  def giai_thua(n):
    if n==1 or n==0:
      return 1
    else:
      return n*giai_thua(n-1)
  s_3=s_3+(x**i)/giai_thua(n)
print(s_3)