# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZ2jyBSHL-_N6bxITNEmkQf4erBy-cZ3

Bài 04. Lập trình thực hiện các công việc sau:
    1. Nhập 3 số a, b, c bất kì
    2. Hãy kiểm tra xem ba số đó có phải là độ dài của các cạnh của một tam giác hay không?
    3. Nếu đúng là tam giác thì xác định là tam giác vuông hay không?
"""

a= float(input('nhap do dai cua a'))
b= float(input('nhap do dai cua b'))
c= float(input('nhap do dai cua c'))
if a+b>c and a+c>b and b+c>a:
  print('a,b,c thoa man la do dai cua mot tam giac')
  if a**2+b**2==c**2 or b**2+c**2==a**2 or a**2+c**2==b**2:
    print('day la 3 canh cua mot tam giac vuong')
  else:
    print('nhap lai gia tri a,b,c')
else: 
  print('nhap lai gia tri a,b,c')