# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYDlEef98TnJMfms-ox4R9euFbs_cJAp

Bài 05.1. Nhập số epsilon < 1 từ bàn phím
    2. Tính e = 1 + 1/1! + 1/2! + ... + 1/n! quá trình dừng khi 1/n! < epsilon.
    3. Đưa kết quả ra màn hình
"""

n= int(input('nhap gia tri cua n'))
e= float(input('nhap gia tri cua epsilon <1'))
import math
s=0
i=1
while 1/math.factorial(i) >=e:
  i+=1
  s=s+ 1/math.factorial(i)
print(s)