# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OMgX7gOhLKWGPbexImV28_mCSbxVfTRI
"""

name = input(' nhap ten cua ban')
print(name)