# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-V8uWOlBRdk2JX3ia4bRdeZqsHBo0iHy

Bài 01. Viết chương trình tìm giá trị lớn nhất và giá trị nhỏ nhất trong các value của dict
"""

my_dict = {1 : 3, 2 : 5, 3: 7, 4 : 9, 5 : 10}
print('giá trị lớn nhất trong dict trên là : ',max(my_dict.values()))
print('giá trị nhỏ nhất trong dict trên là : ',min(my_dict.values()))