# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1334OOvt5O6xXxBBAEAFphCQRsJc2QOD3

Bài 08: Viết chương trình đếm số lần xuất hiện các từ đơn trong một đoạn văn bản
"""

my_string = input('nhập một chuỗi văn bản bất kỳ từ bàn phím : ')
a = my_string.split()
count = {}
for i in a :
  if i in count :
    count[i]+=1
  else : 
    count[i]=1
print(count)