# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XuNQKXz2KAQkwSN8Vi6Oret6Dg-bgRGb

Bài 07. Viết hàm đếm số lần xuất hiện các ký tự trong một String
"""

my_string = input(' nhập string từ bàn phím : ')
count = {}
for i in my_string :
  if i in count :
    count[i]+=1
  else :
    count[i]=1
print(count)