# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-V8uWOlBRdk2JX3ia4bRdeZqsHBo0iHy

Bài 02. Viết chương trình tìm ra top 3 phần tử của dict có key lớn nhất
"""

my_dict = { 5: -5, 10 : -10, -1 : 1, -2 : 2, 6 : -6, -10 : 10, -7 : 7}
key_list = sorted(my_dict.keys(), reverse=True)
for i in key_list[:3]:
  print('3 phần tử lớn nhất là : ', i,':',my_dict[i])