# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wu_m0Ab5QbMJAupZpfGSl8lGbLroRJl

Bài 00. Viết chương trình tính tích value của các phần tử trong một dict
"""

my_dict = {1 : -5, 2 : -10 , 3 : -15, 4 : -20}
a = my_dict.values()
tich = 1
for i in a :
  tich*=i
print(tich)

my_dict = {1 : -5, 2 : -10 , 3 : -15, 4 : -20}
v1 = my_dict.values()
from functools import reduce
print('tích của các phần tử trong dict trên là : ', reduce( lambda a,b : a*b, v1))