# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wNLeAxQsTPDJjZgTD8hpFDsexPoY8BGS

Bài 04. Viết chương trình lấy ra các phần tử key-value xuất hiện trong cả 2 dict
"""

dict_1 = {1 : -1, 2: -2, 3: -3, 4: -4, 5: -5}
dict_2 = {4 : -4, 5: -5 , 6: -6, 7:-7, 8: -8}
print('phần tử chung của hai dict trên là : ', dict(set(dict_2.items()).intersection(set(dict_1.items()))))