# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-V8uWOlBRdk2JX3ia4bRdeZqsHBo0iHy

Bài 05. Viết chương trình tạo dict mới bằng cách trích xuất dữ liệu từ dict ban đầu theo tập các key cho trước
"""

my_dict = {'name': 'Siri', 'age': '20', 'height' : '175cm', 'weight' : '65kg', 'occupation' : 'assistant', ' company' : 'Apple'}
key_1 = ['name', 'occupation', ' company']
for i in key_1:
  new_dict = dict.fromkeys([i],my_dict[i])
  print(new_dict)
# bài này làm thế nào để kết quả chỉ hiển thị trong 1 dict hả thầy? 
# thầy note lại dùm e với, thank u thầy :D

