# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19e9xU750QP18C2aCPjpHLcjPAxLMRLpP

Bài 02. Lập chương trình tính các tổng sau:
    S_1 = 1 + x + x^2 + x^3 + ... + x^n
"""

x= int(input('nhap gia tri cua x'))
n = int(input('nhap gia tri cua n'))
s_1=0
for i in range(n+1):
  s_1=s_1+x**i
print('gia tri cua s_1 la : ',s_1)