# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zn2uRbyK5FGCPNu4IhxoV7NJ3KJ51So9

2.a:    S_1 = 1 + x + x^2 + x^3 + ... + x^n
"""

x= int(input('nhap gia tri cua x'))
n = int(input('nhap gia tri cua n'))
s_1=0
for i in range(n+1):
  s_1=s_1+x**i
print('gia tri cua s_1 la : ',s_1)

"""    S_2 = 1 - x + x^2 - x^3 + ... + (-1)^n.x^n

"""

x= int(input('nhap gia tri cua x'))
n= int(input('nhap gia tri cua n'))
s_2=0
for i in range(n+1):
  s_2=s_2+((-1)**i)*x**i
print('gia tri cua s_2 la :',s_2)

"""    S_3 = 1 + x/1! + x^2/2! + ... + x^n/n!
bài này e ra kết quả chưa đúng mà chưa tìm được lỗi sai, thầy fix dùm em với ạ
"""

x= int(input('nhap gia tri cua x '))
n= int(input('nhap gia tri cua n '))
s_3=0
for i in range(n+1):
  def giai_thua(n):
    if n==1 or n==0:
      return 1
    else:
      return n*giai_thua(n-1)
  s_3=s_3+(x**i)/giai_thua(n)
print(s_3)