# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gL8OCDto9iQOyV5ap_PH8ayX7C3NULOh

bài 1 : giải phương trình bậc 2 : ax^2 + bx + c = 0
"""

a = float(input('nhập giá trị của a: '))
b = float(input('nhập giá trị của b: '))
c = float(input('nhập giá trị của c: '))
if a==0:
  if b==0:
    if c==0:
      print('phương trình có vô số nghiệm')
    else :
      print('phương trình vô nghiệm')
  else :
    print(f'phương trình có nghiệm là x :',-c/b)
else :
  import math
  delta = b**2 -4*a*c
  if delta>0 :
    x1 = (-b + math.sqrt(delta))/(2*a)
    x2 = (-b - math.sqrt(delta))/(2*a)
    print(f'phương trình có nghiệm x1 là :',x1)
    print(f'phương trình có nghiệm x là :',x2)
  elif delta==0:
    print('phương trình có nghiệm kép x1=x2=  ', -b/(2*a))
  else :
    print('phương trình vô nghiệm')