# -*- coding: utf-8 -*-
"""Copy of Untitled54.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/hieubui141/Demo_repo/blob/main/Copy_of_Untitled54.ipynb

Bài 00. Mô phỏng lại trò chơi sau: 
- Người chơi tung 2 con xúc xắc 6 mặt, các mặt có số chấm là: 1, 2, 3, 4, 5, 6
- Quan sát kết quả, tính tổng các mặt hướng lên sau khi 2 con xúc xắc đứng yên
- Lần đầu tiên,
    - Nếu tổng là 7 hoặc 11 => Người chơi THẮNG
    - Nếu tổng là 2, 3 hoặc 12 => Người chơi THUA
    - Nếu tổng là 4, 5, 6, 8, 9 hoặc 10 => Đây sẽ là ĐIỂM của người chơi, và sang vòng tiếp theo
- Để giành được THẮNG, người chơi tiếp tục tung 2 con xúc xắc cho đến khi ra được tổng = ĐIỂM trong lần đầu tiên; 
nếu tung ra được tổng = 7 => Người chơi THUA
Epsilon Bit
•
7 thg 10
"""

import random 
def dice_roll1():
  ''' hàm lấy giá trị ngẫu nhiên con xúc xắc
  '''
  diceroll1 = random.randrange(1,7)
  return diceroll1

def dice_roll2():
  ''' hàm lấy giá trị ngẫu nhiên con xúc xắc
  '''
  diceroll2 = random.randrange(1,7)
  return diceroll2

a = dice_roll1() + dice_roll2()
if a == 7 or a == 11:
  print('thắng với tổng của hai con xúc xắc là : ', a)
elif a ==2 or a == 3 or a == 12 :
  print('tổng hai con xúc xắc của bạn là : ', a,' thua cuộc ')
else :
  print(a)

  def dice_roll3():
    ''' hàm lấy giá trị ngẫu nhiên con xúc xắc
    '''
    diceroll3 = random.randrange(1,7)
    return diceroll3

  def dice_roll4():
    ''' hàm lấy giá trị ngẫu nhiên con xúc xắc
    '''
    diceroll4 = random.randrange(1,7)
    return diceroll4

  b = dice_roll3() + dice_roll4()
  while True:
   if b == a :
    print(' thắng cuộc với tổng hai lần đều bằng : ',b)
    break
   elif b == 7 :
    print('lần thứ hai của bạn có tổng là : ',b, 'thua rồi')
    break
   else :
    print('tổng lần hai của bạn là : ', b, 'thua rồi') 
    break