# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1GXxhAghU1HAw_mZRT57cKAxhNPdLY8

Bài 00: Viết chương trình sinh một tuple chứa các phần tử có các kiểu dữ liệu khác nhau. Sau đó, unpack các phần tử trong một tuple.
"""

a,b,c,d = 3, 2, 1, 'xyz'
print(a)
print(b)
print(c)
print(d)