# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEAmLXVK2ORj6V8PFBe0xkvl-Uk05M6-

Bài 09: Viết chương trình tính tổng và tìm giá trị lớn nhất trong tuple chứa các số thực.
"""

my_tuple = 5 , 10 ,15 ,20 ,-15, 15, -10
sum_tuple = 0
for i in my_tuple :
  sum_tuple += i
  print('tổng : ', sum_tuple)
print('giá trị lớn nhất trong tuple trên là : ', max(my_tuple))

my_tuple = 5 , 10 ,15 ,20 ,-15, 15, -10
from functools import reduce 
print('tổng của các phần tử trong tuple là : ', reduce( lambda a,b : a+b, my_tuple ))
print('giá trị lớn nhất của phần tử trong tuple là : ', reduce(lambda a,b : a if a<b else b, my_tuple))