# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1GXxhAghU1HAw_mZRT57cKAxhNPdLY8

Bài 01: Viết chương trình chuyển một tuple sang thành list và ngược lại từ list sang tuple
"""

my_tuple = [10, 20 , 30 ,40 , 'hello world']
tuple_list = list(my_tuple)
list_tuple= tuple(tuple_list)
print('list mới là : ',tuple_list)
print('tuple mới là : ',list_tuple)