# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1llrxMTUlWdhMl761TKx_LIPjMErCTw98

Bài 07: Viết chương trình kiểm tra 2 tuple có phần tử chung hay không.
"""

tuple_1 = 1, 2, 3, 4, 'py', 'thon'
tuple_2 = 'python', 9, 8, 7, 6, 5
for i in tuple_1 : 
  if i in tuple_2 :
    print('hai tuple này có phần tử chung')
    break
  if i not in tuple_2 :
    print('không có phần tử chung')