# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1GXxhAghU1HAw_mZRT57cKAxhNPdLY8

Bài 02: Viết chương trình đảo ngược một tuple.
"""

tuple_1 = 2019, 'covid', 'pandemic', 'vaccine', 2021
new_tuple_1= list(tuple_1)
new_tuple_1.reverse()
new_tuple= tuple(new_tuple_1)
print(new_tuple)