# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1GXxhAghU1HAw_mZRT57cKAxhNPdLY8

Bài 03: Viết chương trình đếm số lượng các phần tử trong một list đến khi gặp một phần tử kiểu tuple.
"""

A = [1, 2 ,3 , 'Apple', 'Samsung', 2, 25, 11, (3,2,1), 3.14]
count=0
for i in A:
  count+=1
  if type(i) == tuple:
    break
  print(count)