# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEAmLXVK2ORj6V8PFBe0xkvl-Uk05M6-

Bài 12. Viết chương trình để thử lại các phương thức của Set theo danh sách sau
        set.difference_update(other_set)
        set.intersection_update(other_set)
        set.isdisjoint(other_set)
        set.issubset(other_set)
        set.issuperset(other_set)
        set.symmetric_difference_update(other_set)
"""

set_1 = {1 , 3, 5, 7, 9, 10 }
set_2 = {2, 4, 6 ,8, 10, 7, 9}
print(set_1.difference_update(set_2))
print(set_1.intersection_update(set_2))
print(set_1.isdisjoint(set_2))
print(set_1.issubset(set_2))
print(set_1.issuperset(set_2))
print(set_1.symmetric_difference_update(set_2))