# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEAmLXVK2ORj6V8PFBe0xkvl-Uk05M6-

Bài 08: Viết chương trình kiểm tra xem tất cả các phần tử trong tuple có giống nhau hay không.
"""

my_tuple = 1,1,1,1,1,1
if len(set(my_tuple)) == 1 :
  print('các phần tử trong tuple là giống nhau')
else : 
  print('các phần tử trong tuple là khác nhau')