# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wcjNh4OHiWZbgRbp-wUyAU1D5SAErg7a

Bài 05: Viết chương trình tìm ra tuple có phần tử thứ 2 là nhỏ nhất từ một list chứa các tuple.
"""

your_list = [ (1, 3, 5), ( 3.14, 4.23, 3.5), (4, 3, 2, 1), ( -5, -7, -8)]
x = sorted(your_list,key= lambda x : x[1])
print(x[0])