# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pWqVMd0fD4OXFPhXIlfNFL5pWbKyHAMw

Bài 06: Viết chương trình in ra phần tử thứ 4 và phần tử thứ 4 từ cuối lên trong một tuple.
"""

my_tuple = ( 1, 2 ,3 ,4, 5, 6, 7, 8, 9, 10, 'a', 'b', 'c','d', 'e', 'f')
print('phần tử thứ tư là : ' ,my_tuple[3])
print('phần tử thứ tư từ cuối lên là : ',my_tuple[-4])