# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GI93KK6uzMnWoeEhsKKudxrXo9c4Wzp

Bài 02. Viết hàm
        def reverse_string(str)
    trả lại chuỗi đảo ngược của chuỗi str
"""

def reverse_string(str):
  '''
  Viết hàm def reverse_string(str) trả lại chuỗi đảo ngược của chuỗi str
  '''
  return str[::-1]
print(reverse_string('hi how are you today?'))