# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GI93KK6uzMnWoeEhsKKudxrXo9c4Wzp

Bài 01. Viết hàm
        def max_min(*numbers)
    trả lại cả giá trị max, min của nhiều số được truyền vào
"""

def max_min(*numbers) :
  """ 
  hàm tìm giá trị lớn nhất và nhỏ nhất được truyền vào 
  """
  max_number = max(numbers)
  min_number = min(numbers)
  return max_number, min_number
print('giá trị lớn nhất và nhỏ nhất lần lượt là : ', max_min(1,2,3,4,5))