# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZW3nVoLCGjEXSQwucrf2lVmyq11AsPu

Bài 07. Viết hàm
        def body_mass_index(m, h)
    để tính toán chỉ số BMI của một người với cân nặng m (kg), chiều cao h (m)
      Viết hàm
        def bmi_information(m, h)
    để đưa ra thông tin về chỉ số BMI cũng như phân loại mức độ gầy - béo của người cân nặng m, chiều cao h
"""

def body_mass_index(m,h):
  '''  Viết hàm def body_mass_index(m, h) để tính toán chỉ số BMI của một người với cân nặng m (kg), chiều cao h (m)
  '''
  return round(((m)/(h**2)),2)
def bmi_information(m,h) :
  if body_mass_index(m,h) <18.5:
    return 'Bạn đang có dấu hiệu thiếu cân'
  elif 18.5<= body_mass_index(m,h) <=22.9:
    return 'Bạn đang sở hữu cân nặng lý tưởng so với chiều cao'
  elif 23<= body_mass_index(m,h) <= 24.9:
    return 'Chỉ số cho thấy bạn đang có dấu hiệu thừa cân'
  elif 25<= body_mass_index(m,h) <=29.9:
    return 'Chỉ số cho thấy bạn đang có dấu hiệu gần béo phì'
  elif body_mass_index(m,h) >=30 :
    return 'Béo phì rồi nha bạn ơi'
m = float(input(' nhập cân nặng (kg) : '))
h = float(input(' chiều cao (m) của bạn : '))
print('chỉ số BMI cơ thể của bạn là : ' ,body_mass_index(m,h),'và' ,bmi_information(m,h))