# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W35shwIMEm2REaK--8O2UN6JPUFxe3zy

Bài 05. Viết hàm
        def count_upper_lower(str)
    trả lại số lượng chữ cái viết hoa, số lượng chữ cái viết thường trong chuỗi str
"""

def count_upper_lower(str):
  ''' Viết hàm def count_upper_lower(str) trả lại số lượng chữ cái viết hoa, số lượng chữ cái viết thường trong chuỗi str
  '''
  count_upper = 0
  count_lower = 0
  for i in str:
    if 'A' <= i <= 'Z':
      count_upper +=1
    if 'a' <= i <= 'z':
      count_lower +=1
  return count_upper, count_lower
str = input('nhập str : ')
print('số lượng chữ cái viết hoa và viết thường lần lượt là : ',count_upper_lower(str))