# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GI93KK6uzMnWoeEhsKKudxrXo9c4Wzp

Bài 03. Viết hàm
        def is_perfect(n)
    để kiểm tra xem số tự nhiên n có phải là số hoàn hảo hay ko, trả lại True nếu có, False nếu không.
"""

def is_perfect(n):
  ''' Viết hàm def is_perfect(n) để kiểm tra xem số tự nhiên n có phải là số hoàn hảo hay ko, trả lại True nếu có, False nếu không.
  '''
  tong = 0
  for i in range(1,n):
    if (n % i) == 0 :
      tong += i
  if tong == n :
    return True
  else :
    return False
print(is_perfect(28))