# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lne__0KuzYbOGR0MC5mm9Hxemt9H1rRR

Bài 08. Viết hàm
        def change_upper_lower(str)
    chuyển toàn bộ các ký tự in hoa sang in thường và in thường thành in hoa trong str
"""

def change_upper_lower(str) : 
  ''' hàm def change_upper_lower(str) chuyển toàn bộ các ký tự in hoa sang in thường và in thường thành in hoa trong str
  '''
  new_str = ''
  for i in str :
    if 'a'<= i <='z' :
      new_str += chr(ord(i)-32)
    elif 'A' <= i <= 'Z' :
      new_str += chr(ord(i)+32)
  return new_str
str = input('nhập vào một chuỗi bất kỳ : ')
print(change_upper_lower(str))

def change_upper_lower(str) : 
  ''' hàm def change_upper_lower(str) chuyển toàn bộ các ký tự in hoa sang in thường và in thường thành in hoa trong str
  '''
  return str.swapcase()
str = input('nhập vào một chuỗi bất kỳ : ')
print(change_upper_lower(str))

