# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZW3nVoLCGjEXSQwucrf2lVmyq11AsPu

Bài 06. Viết hàm
        def is_pangram(str, alphabet)
    đề kiểm tra xem chuỗi str có phải là Pangram không, trả lại True nếu có, False nếu không
"""

def is_pangram(str):
  alphabet = 'abcdefghijklmnopqrstuvwxyz'
  for i in alphabet : 
    if i not in str.lower() :
      return False
    else :
      return True
print(is_pangram('Abcdefghijklmnopqrstuvwxyz'))