# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ubEYUUNLj3TihI4myAwHpp4Q-c7Ihncj
"""

s= input('nhap chuoi s tu ban phim: ')
for i in range(len(s)):
  if s[i]==s[0]:
    print(s.replace(s[0],'$'))