# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVDgRP1vSnbuCbg0ULohxYfmmQPZ4I1m

Bài 03. Viết chương trình tìm ra ký tự lớn nhất và ký tự nhỏ nhất của một chuỗi nhập từ bán phím.
"""

s = input('nhap chuoi s tu ban phim : ')
print(max(s))
print(min(s))