# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_EPFp_11kSUo6F9NVZFOn1zJctAD7qrt

Bài 02. Viết chương trình sinh ra một chuỗi từ 2 ký tự đầu và 2 ký tự cuối trong chuỗi được nhập vào, nếu độ dài chuỗi nhỏ hơn 2 thì in ra chuỗi rỗng.
"""

s=input('nhap chuoi tu ban phim : ')
if len(s)<2:
  print('')
else:
  a=s[:2]+s[-2:]
  print(a)