# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldqxQoH8PDLDPrhWNx9UbHs9TCNoYgtl

Bài 06. Viết chương trình
     Nhập vào 1 chuỗi từ bàn phím, Nhập vào 1 ký tự từ bàn phím, Tìm và in ra tất cả các vị trí của ký tự vừa nhập trong chuỗi đã nhập
"""

s= input('nhập một chuỗi từ bàn phím: ')
a = input('nhập một ký tự từ bàn phím : ')
for i in range(len(s)):
  if a==s[i]:
    print(i,end=" ")