# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXRg0sqtULNfGFzqJpqMR-5GmddnOuuI

Bài 05. Viết chương trình in ra các ký tự số trong chuỗi được nhập từ bàn phím
"""

s=input('nhập chuỗi ký tự từ bàn phím : ')
for i in range(len(s)) :
  print(ord(s[i]))